[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_22", "npm-9_x"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-interaction",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]
